package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.AncestorListener;
import model.TableModel;

/**
 *
 * @author husban
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardV
     */
    public DashboardView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        LoginsBtn = new javax.swing.JButton();
        SecureNotesBtn = new javax.swing.JButton();
        GenerateBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        LoginsPanel = new javax.swing.JPanel();
        LoginsHeader = new javax.swing.JLabel();
        AddLoginsButton = new javax.swing.JButton();
        PasswordPanel = new javax.swing.JPanel();
        GeneratePanel = new javax.swing.JPanel();
        GenerateHeader = new javax.swing.JLabel();
        GeneratedPasswordField = new javax.swing.JTextField();
        SecureNotesPanel = new javax.swing.JPanel();
        SecureNotesHeader = new javax.swing.JLabel();
        AddSecureNotesButton = new javax.swing.JButton();
        AddLoginsPanel = new javax.swing.JPanel();
        AddLoginsHeader = new javax.swing.JLabel();
        WebsiteLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        WebsiteInputField = new javax.swing.JTextField();
        PasswordInputField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        AddSecureNotesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        SideBar.setBackground(new java.awt.Color(51, 51, 51));

        LoginsBtn.setText("Logins");

        SecureNotesBtn.setText("Secure Notes");

        GenerateBtn.setText("Generate");

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SecureNotesBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(GenerateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(LoginsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(GenerateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(SecureNotesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(SideBar);

        MainPanel.setLayout(new java.awt.CardLayout());

        LoginsHeader.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        LoginsHeader.setText("Logins");

        AddLoginsButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        AddLoginsButton.setText("Add Login");

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginsPanelLayout = new javax.swing.GroupLayout(LoginsPanel);
        LoginsPanel.setLayout(LoginsPanelLayout);
        LoginsPanelLayout.setHorizontalGroup(
            LoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LoginsHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(AddLoginsButton)
                .addGap(17, 17, 17))
            .addComponent(PasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginsPanelLayout.setVerticalGroup(
            LoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginsPanelLayout.createSequentialGroup()
                .addGroup(LoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginsPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LoginsHeader))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddLoginsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(LoginsPanel, "card2");

        GenerateHeader.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        GenerateHeader.setText("Generated Password");

        GeneratedPasswordField.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout GeneratePanelLayout = new javax.swing.GroupLayout(GeneratePanel);
        GeneratePanel.setLayout(GeneratePanelLayout);
        GeneratePanelLayout.setHorizontalGroup(
            GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneratePanelLayout.createSequentialGroup()
                .addGroup(GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneratePanelLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(GenerateHeader))
                    .addGroup(GeneratePanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(GeneratedPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        GeneratePanelLayout.setVerticalGroup(
            GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneratePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(GenerateHeader)
                .addGap(76, 76, 76)
                .addComponent(GeneratedPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        MainPanel.add(GeneratePanel, "card3");

        SecureNotesHeader.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        SecureNotesHeader.setText("Secure Notes");

        AddSecureNotesButton.setText("Add Notes");

        javax.swing.GroupLayout SecureNotesPanelLayout = new javax.swing.GroupLayout(SecureNotesPanel);
        SecureNotesPanel.setLayout(SecureNotesPanelLayout);
        SecureNotesPanelLayout.setHorizontalGroup(
            SecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecureNotesPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(SecureNotesHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(AddSecureNotesButton)
                .addGap(36, 36, 36))
        );
        SecureNotesPanelLayout.setVerticalGroup(
            SecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecureNotesPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(SecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecureNotesHeader)
                    .addComponent(AddSecureNotesButton))
                .addContainerGap(403, Short.MAX_VALUE))
        );

        MainPanel.add(SecureNotesPanel, "card4");

        AddLoginsHeader.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        AddLoginsHeader.setText("Add Login Credentials");

        WebsiteLabel.setText("Website:");

        PasswordLabel.setText("Password:");

        SubmitButton.setText("Submit");

        javax.swing.GroupLayout AddLoginsPanelLayout = new javax.swing.GroupLayout(AddLoginsPanel);
        AddLoginsPanel.setLayout(AddLoginsPanelLayout);
        AddLoginsPanelLayout.setHorizontalGroup(
            AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(AddLoginsHeader))
                    .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WebsiteLabel)
                            .addComponent(PasswordLabel))
                        .addGap(151, 151, 151)
                        .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WebsiteInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(PasswordInputField)))
                    .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(SubmitButton)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        AddLoginsPanelLayout.setVerticalGroup(
            AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(AddLoginsHeader)
                .addGap(87, 87, 87)
                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WebsiteLabel)
                    .addComponent(WebsiteInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(SubmitButton)
                .addGap(110, 110, 110))
        );

        MainPanel.add(AddLoginsPanel, "card5");

        javax.swing.GroupLayout AddSecureNotesPanelLayout = new javax.swing.GroupLayout(AddSecureNotesPanel);
        AddSecureNotesPanel.setLayout(AddSecureNotesPanelLayout);
        AddSecureNotesPanelLayout.setHorizontalGroup(
            AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        AddSecureNotesPanelLayout.setVerticalGroup(
            AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        MainPanel.add(AddSecureNotesPanel, "card6");

        getContentPane().add(MainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PasswordPanelActionListerner(AncestorListener evt) {
        LoginsPanel.addAncestorListener(evt);
    }
    
    public void DisplayTable(ArrayList<TableModel> list){
        int size = list.size();
        Object[][] data = new Object[size][];
        for(int i=0;i<size;i++){
            data[i] = new Object[]{list.get(i).getID(),list.get(i).getSite(),list.get(i).getPwd(),list.get(i).getDate()};
        }
        String[] col = new String[]{"ID","Website","Password","Date Created"};
        JTable Table = new JTable(data, col);
        JScrollPane scroll = new JScrollPane(Table);
        scroll.getViewport().setBackground(Color.WHITE);
        scroll.setSize(LoginsPanel.getWidth(), LoginsPanel.getHeight());
        PasswordPanel.add(scroll);
        PasswordPanel.repaint();
    }
    
    public void showMessage() {
        JLabel msgLabel = new JLabel("Click Add button to store password", JLabel.CENTER);
        msgLabel.setSize(LoginsPanel.getWidth(), 50);
        PasswordPanel.add(msgLabel);
        PasswordPanel.repaint();
    }
    
    public void AddLoginsBtnActionListener(ActionListener action) {
        AddLoginsButton.addActionListener(action);
    }

    public void GenerateBtnActionListener(ActionListener action) {
        GenerateBtn.addActionListener(action);
    }
    
    public void LoginsBtnActionListener(ActionListener action) {
        LoginsBtn.addActionListener(action);
    }
    
    public void SecureNotesBtnActionListener(ActionListener action) {
        SecureNotesBtn.addActionListener(action);
    }
    
    public void SubmitBtnActionListener(ActionListener action) {
        SubmitButton.addActionListener(action);
    }
    
    public void DisplayGeneratedPasswordPanel(String generatedPassword) {
//        JOptionPane.showMessageDialog(this, new JPanel().add(new JTextField(generatedPassword)), "Generated Password", JOptionPane.INFORMATION_MESSAGE);
          GeneratedPasswordField.setText(generatedPassword);
          MainPanel.removeAll();
          MainPanel.add(GeneratePanel);
          MainPanel.repaint();
          MainPanel.revalidate();          
    }
    
    public void DisplayLoginsPanel() {
          MainPanel.removeAll();
          MainPanel.add(LoginsPanel);
          MainPanel.repaint();
          MainPanel.revalidate();          
    }
    
    public void DisplaySecureNotesPanel() {
          MainPanel.removeAll();
          MainPanel.add(SecureNotesPanel);
          MainPanel.repaint();
          MainPanel.revalidate();          
    }
    
    public void DisplayAddLoginsPanel() {
          MainPanel.removeAll();
          MainPanel.add(AddLoginsPanel);
          MainPanel.repaint();
          MainPanel.revalidate();           
    }
    
    public String getWebsite() {
        return WebsiteInputField.getText();
    }
    
    public String getPassword() {
        return PasswordInputField.getText();
    }
    
    public void clearWebsiteField() {
        WebsiteInputField.setText("");
    }
    
    public void clearPasswordField() {
        PasswordInputField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLoginsButton;
    private javax.swing.JLabel AddLoginsHeader;
    private javax.swing.JPanel AddLoginsPanel;
    private javax.swing.JButton AddSecureNotesButton;
    private javax.swing.JPanel AddSecureNotesPanel;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JLabel GenerateHeader;
    private javax.swing.JPanel GeneratePanel;
    private javax.swing.JTextField GeneratedPasswordField;
    private javax.swing.JButton LoginsBtn;
    private javax.swing.JLabel LoginsHeader;
    private javax.swing.JPanel LoginsPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField PasswordInputField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JButton SecureNotesBtn;
    private javax.swing.JLabel SecureNotesHeader;
    private javax.swing.JPanel SecureNotesPanel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField WebsiteInputField;
    private javax.swing.JLabel WebsiteLabel;
    // End of variables declaration//GEN-END:variables
}
