package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.AncestorListener;
import model.NotesModel;
import model.TableModel;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Husban
 * @author Harshit
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardV
     */
    public DashboardView() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        LoginsBtn = new javax.swing.JButton();
        SecureNotesBtn = new javax.swing.JButton();
        GenerateBtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        LoginsPanel = new javax.swing.JPanel();
        LoginsHeader = new javax.swing.JLabel();
        AddLoginsButton = new javax.swing.JButton();
        PasswordPanel = new javax.swing.JPanel();
        GeneratePanel = new javax.swing.JPanel();
        GenerateHeader = new javax.swing.JLabel();
        GeneratedPasswordField = new javax.swing.JTextField();
        PasswordLengthSlider = new javax.swing.JSlider();
        PasswordLengthLabel = new javax.swing.JLabel();
        PasswordMinLengthLabel = new javax.swing.JLabel();
        PasswordMinLengthLabel1 = new javax.swing.JLabel();
        MixedCaseCheckBox = new javax.swing.JCheckBox();
        PunctuationCheckBox = new javax.swing.JCheckBox();
        NumbersCheckBox = new javax.swing.JCheckBox();
        SecureNotesPanel = new javax.swing.JPanel();
        AddSecureNotesButton = new javax.swing.JButton();
        SecureNotesHeader = new javax.swing.JLabel();
        SecureNotesDisplay = new javax.swing.JPanel();
        AddLoginsPanel = new javax.swing.JPanel();
        AddLoginsHeader = new javax.swing.JLabel();
        WebsiteLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        WebsiteInputField = new javax.swing.JTextField();
        PasswordInputField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        AddSecureNotesPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        TitleArea = new javax.swing.JTextField();
        NotesLabel = new javax.swing.JLabel();
        TextArea = new javax.swing.JTextField();
        Heading = new javax.swing.JLabel();
        NotesSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        SideBar.setBackground(new java.awt.Color(51, 51, 51));

        LoginsBtn.setText("Logins");

        SecureNotesBtn.setText("Secure Notes");

        GenerateBtn.setText("Generate");

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SecureNotesBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(GenerateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(LoginsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(GenerateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(SecureNotesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(SideBar);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        LoginsPanel.setBackground(new java.awt.Color(255, 255, 255));

        LoginsHeader.setBackground(new java.awt.Color(255, 255, 255));
        LoginsHeader.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        LoginsHeader.setText("Logins");

        AddLoginsButton.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        AddLoginsButton.setText("Add Login");

        PasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginsPanelLayout = new javax.swing.GroupLayout(LoginsPanel);
        LoginsPanel.setLayout(LoginsPanelLayout);
        LoginsPanelLayout.setHorizontalGroup(
            LoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LoginsHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(AddLoginsButton)
                .addGap(17, 17, 17))
            .addComponent(PasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginsPanelLayout.setVerticalGroup(
            LoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginsPanelLayout.createSequentialGroup()
                .addGroup(LoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginsPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LoginsHeader))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddLoginsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(LoginsPanel, "card1");

        GenerateHeader.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        GenerateHeader.setText("Generated Password");

        GeneratedPasswordField.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        GeneratedPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        PasswordLengthSlider.setMaximum(20);
        PasswordLengthSlider.setMinimum(8);
        PasswordLengthSlider.setValue(8);

        PasswordLengthLabel.setText("Password Lenght: 8 - 20");

        PasswordMinLengthLabel.setText("8");

        PasswordMinLengthLabel1.setText("20");

        MixedCaseCheckBox.setSelected(true);
        MixedCaseCheckBox.setText("Mixed Case");

        PunctuationCheckBox.setSelected(true);
        PunctuationCheckBox.setText("Punctuation");

        NumbersCheckBox.setSelected(true);
        NumbersCheckBox.setText("Numbers");

        javax.swing.GroupLayout GeneratePanelLayout = new javax.swing.GroupLayout(GeneratePanel);
        GeneratePanel.setLayout(GeneratePanelLayout);
        GeneratePanelLayout.setHorizontalGroup(
            GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneratePanelLayout.createSequentialGroup()
                .addGroup(GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneratePanelLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(GenerateHeader))
                    .addGroup(GeneratePanelLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(PasswordLengthLabel))
                    .addGroup(GeneratePanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(GeneratedPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneratePanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GeneratePanelLayout.createSequentialGroup()
                                .addComponent(MixedCaseCheckBox)
                                .addGap(49, 49, 49)
                                .addComponent(PunctuationCheckBox)
                                .addGap(32, 32, 32))
                            .addGroup(GeneratePanelLayout.createSequentialGroup()
                                .addComponent(PasswordMinLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordLengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordMinLengthLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumbersCheckBox))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        GeneratePanelLayout.setVerticalGroup(
            GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneratePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(GenerateHeader)
                .addGap(76, 76, 76)
                .addComponent(GeneratedPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(PasswordLengthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordMinLengthLabel)
                    .addComponent(PasswordMinLengthLabel1))
                .addGap(75, 75, 75)
                .addGroup(GeneratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MixedCaseCheckBox)
                    .addComponent(PunctuationCheckBox)
                    .addComponent(NumbersCheckBox))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        MainPanel.add(GeneratePanel, "card2");

        SecureNotesPanel.setBackground(new java.awt.Color(255, 255, 255));
        SecureNotesPanel.setPreferredSize(new java.awt.Dimension(708, 496));

        AddSecureNotesButton.setText("Add Notes");

        SecureNotesHeader.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        SecureNotesHeader.setText("Secure Notes");

        SecureNotesDisplay.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SecureNotesDisplayLayout = new javax.swing.GroupLayout(SecureNotesDisplay);
        SecureNotesDisplay.setLayout(SecureNotesDisplayLayout);
        SecureNotesDisplayLayout.setHorizontalGroup(
            SecureNotesDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SecureNotesDisplayLayout.setVerticalGroup(
            SecureNotesDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SecureNotesPanelLayout = new javax.swing.GroupLayout(SecureNotesPanel);
        SecureNotesPanel.setLayout(SecureNotesPanelLayout);
        SecureNotesPanelLayout.setHorizontalGroup(
            SecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecureNotesPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(SecureNotesHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(AddSecureNotesButton)
                .addGap(36, 36, 36))
            .addComponent(SecureNotesDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SecureNotesPanelLayout.setVerticalGroup(
            SecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecureNotesPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(SecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecureNotesHeader)
                    .addComponent(AddSecureNotesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SecureNotesDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(SecureNotesPanel, "card3");

        AddLoginsHeader.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        AddLoginsHeader.setText("Add Login Credentials");

        WebsiteLabel.setText("Website:");

        PasswordLabel.setText("Password:");

        SubmitButton.setText("Submit");

        javax.swing.GroupLayout AddLoginsPanelLayout = new javax.swing.GroupLayout(AddLoginsPanel);
        AddLoginsPanel.setLayout(AddLoginsPanelLayout);
        AddLoginsPanelLayout.setHorizontalGroup(
            AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(AddLoginsHeader))
                    .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitButton)
                            .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WebsiteLabel)
                                    .addComponent(PasswordLabel))
                                .addGap(151, 151, 151)
                                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(WebsiteInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(PasswordInputField))))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        AddLoginsPanelLayout.setVerticalGroup(
            AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLoginsPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(AddLoginsHeader)
                .addGap(87, 87, 87)
                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WebsiteLabel)
                    .addComponent(WebsiteInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(AddLoginsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(SubmitButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        MainPanel.add(AddLoginsPanel, "card4");

        AddSecureNotesPanel.setBackground(new java.awt.Color(255, 255, 255));

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TitleLabel.setText("Title");

        NotesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NotesLabel.setText("Notes");

        Heading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Add Notes");

        NotesSubmit.setText("Submit");

        javax.swing.GroupLayout AddSecureNotesPanelLayout = new javax.swing.GroupLayout(AddSecureNotesPanel);
        AddSecureNotesPanel.setLayout(AddSecureNotesPanelLayout);
        AddSecureNotesPanelLayout.setHorizontalGroup(
            AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSecureNotesPanelLayout.createSequentialGroup()
                .addGroup(AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSecureNotesPanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSecureNotesPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NotesSubmit)
                            .addGroup(AddSecureNotesPanelLayout.createSequentialGroup()
                                .addGroup(AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NotesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                .addGap(75, 75, 75)
                                .addGroup(AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TitleArea, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                    .addComponent(TextArea))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        AddSecureNotesPanelLayout.setVerticalGroup(
            AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSecureNotesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Heading)
                .addGap(52, 52, 52)
                .addGroup(AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleLabel))
                .addGap(59, 59, 59)
                .addGroup(AddSecureNotesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(NotesSubmit)
                .addGap(14, 14, 14))
        );

        MainPanel.add(AddSecureNotesPanel, "card5");

        getContentPane().add(MainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void PasswordPanelActionListerner(AncestorListener evt) {
        PasswordPanel.addAncestorListener(evt);
    }
    
    public void SecureNotesDisplayActionListerner(AncestorListener evt){
        SecureNotesDisplay.addAncestorListener(evt);
    }
   
    //  Password Panel data display 
    public void showPasswordPanelMessage() {
        JLabel msgLabel = new JLabel("Click Add button to store password", JLabel.CENTER);
        msgLabel.setSize(PasswordPanel.getWidth(), 50);
        PasswordPanel.removeAll();
        PasswordPanel.add(msgLabel);
        PasswordPanel.repaint();
    }
    
    public void DisplayUserData(ArrayList<TableModel> list){
        int size = list.size();
        JPanel panel = new JPanel();
        GridLayout layout = new GridLayout(size, 1);
        panel.setLayout(layout);        
        for(int i=0;i<size;i++){
            DataView dataView = new DataView(
                    list.get(i).getSite(),
                    list.get(i).getPwd(),
                    "Pwd",
                    list.get(i).getID()
            );
            dataView.setVisible(true);
            panel.add(dataView);    
        }   
        JScrollPane scroll = null;
        if (size > 4) {
            scroll = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scroll.setSize(PasswordPanel.getWidth(),PasswordPanel.getHeight());
        } else {
            scroll = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scroll.setSize(PasswordPanel.getWidth(),panel.getPreferredSize().height);
        }
        scroll.getViewport().setBackground(Color.WHITE);
        scroll.setBorder(BorderFactory.createEmptyBorder());
        PasswordPanel.removeAll();
        PasswordPanel.add(scroll);
        PasswordPanel.repaint();
    }
    
    //  Secure Notes Panel data display
    public void showSecureNotesMessage() {
        JLabel msgLabel = new JLabel("Click Add button to store notes", JLabel.CENTER);
        msgLabel.setSize(SecureNotesDisplay.getWidth(), 50);
        SecureNotesDisplay.removeAll();
        SecureNotesDisplay.add(msgLabel);
        SecureNotesDisplay.repaint();
    }
    
    public void DisplayUserNotes(ArrayList<NotesModel> list){
        int size = list.size();
        JPanel panel = new JPanel();
        GridLayout layout = new GridLayout(size, 1);
        panel.setLayout(layout);        
        for(int i=0;i<size;i++){
            DataView dataView = new DataView(
                    list.get(i).getTitle(),
                    list.get(i).getNotes(),
                    "Notes",
                    list.get(i).getID()                    
            );
            dataView.setVisible(true);
            panel.add(dataView);
        }    
        JScrollPane scroll=null;
        if (size > 4) {
            scroll = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scroll.setSize(SecureNotesDisplay.getWidth(),SecureNotesDisplay.getHeight());
        } else {
            scroll = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scroll.setSize(SecureNotesDisplay.getWidth(),panel.getPreferredSize().height);
        }
        scroll.getViewport().setBackground(Color.WHITE);
        SecureNotesDisplay.removeAll();
        SecureNotesDisplay.add(scroll);
        SecureNotesDisplay.repaint();
    }
    
    //  Button Actions Listeners
    public void AddLoginsBtnActionListener(ActionListener action) {
        AddLoginsButton.addActionListener(action);
    }
    
    public void DisplayAddLoginsPanel() {
        CardLayout cardLayout = (CardLayout)MainPanel.getLayout();
        cardLayout.show(MainPanel, "card4");
    }
    
    public void GenerateBtnActionListener(ActionListener action) {
        GenerateBtn.addActionListener(action);
    }
    
    public void DisplayGeneratedPasswordPanel(String generatedPassword) {
          GeneratedPasswordField.setText(generatedPassword);
          CardLayout cardLayout = (CardLayout)MainPanel.getLayout();
          cardLayout.show(MainPanel, "card2");         
    }    
    
    public void LoginsBtnActionListener(ActionListener action) {
        LoginsBtn.addActionListener(action);
    }    
    
    public void DisplayLoginsPanel() {
          CardLayout cardLayout = (CardLayout)MainPanel.getLayout();
          cardLayout.show(MainPanel, "card1");      
    }    
    
    public void SubmitBtnActionListener(ActionListener action) {
        SubmitButton.addActionListener(action);
    }   
    
    public void SecureNotesBtnActionListener(ActionListener action) {
        SecureNotesBtn.addActionListener(action);
    }
    
    public void DisplaySecureNotesPanel() {    
        CardLayout cardLayout = (CardLayout)MainPanel.getLayout();
        cardLayout.show(MainPanel, "card3");        
    }   
    
    public void SecureNotesAddBtnActionListener(ActionListener action){
        AddSecureNotesButton.addActionListener(action);
    } 
    
    public void PasswordLenghtSliderChangeListener(ChangeListener change) {
        PasswordLengthSlider.addChangeListener(change);
    }
    
    public void CheckBoxActionListener(ActionListener action) {
        MixedCaseCheckBox.addActionListener(action);
        PunctuationCheckBox.addActionListener(action);
        NumbersCheckBox.addActionListener(action);
    }
    
    public void DisplaySecureNotesArea() {
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, "card5");
    }
    
    public void NotesSubmitActionListener(ActionListener action){
        NotesSubmit.addActionListener(action);
    }    
    
    //  Utility Methods
    public String getWebsite() {
        return WebsiteInputField.getText();
    }
    
    public String getPassword() {
        return PasswordInputField.getText();
    }
    
    public String getNotesTitle() {
        return TitleArea.getText();
    }
    
    public String getSecureNotesTxt() {
        return TextArea.getText();
    }
    
    public int getPasswordLength() {
        return PasswordLengthSlider.getValue();
    }
    
    public boolean getMixedCaseStatus() {
        return MixedCaseCheckBox.isSelected();
    }
    
    public boolean getPunctuationStatus() {
        return PunctuationCheckBox.isSelected();
    }
    
    public boolean getNumberStatus() {
        return NumbersCheckBox.isSelected();
    }
       
    public void clearWebsiteField() {
        WebsiteInputField.setText("");
    }
    
    public void clearPasswordField() {
        PasswordInputField.setText("");
    }
    
    public void clearTitleField(){
        TitleArea.setText("");
    }
    
    public void clearTextField(){
        TextArea.setText("");
    }
    
    public void showSuccess(String succMsg){
        JOptionPane.showMessageDialog(this,succMsg,"Credentials",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void showError(String errorMsg){
        JOptionPane.showMessageDialog(this, errorMsg,"Credentials",JOptionPane.WARNING_MESSAGE);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLoginsButton;
    private javax.swing.JLabel AddLoginsHeader;
    private javax.swing.JPanel AddLoginsPanel;
    private javax.swing.JButton AddSecureNotesButton;
    private javax.swing.JPanel AddSecureNotesPanel;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JLabel GenerateHeader;
    private javax.swing.JPanel GeneratePanel;
    private javax.swing.JTextField GeneratedPasswordField;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton LoginsBtn;
    private javax.swing.JLabel LoginsHeader;
    private javax.swing.JPanel LoginsPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JCheckBox MixedCaseCheckBox;
    private javax.swing.JLabel NotesLabel;
    private javax.swing.JButton NotesSubmit;
    private javax.swing.JCheckBox NumbersCheckBox;
    private javax.swing.JTextField PasswordInputField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLengthLabel;
    private javax.swing.JSlider PasswordLengthSlider;
    private javax.swing.JLabel PasswordMinLengthLabel;
    private javax.swing.JLabel PasswordMinLengthLabel1;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JCheckBox PunctuationCheckBox;
    private javax.swing.JButton SecureNotesBtn;
    private javax.swing.JPanel SecureNotesDisplay;
    private javax.swing.JLabel SecureNotesHeader;
    private javax.swing.JPanel SecureNotesPanel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField TextArea;
    private javax.swing.JTextField TitleArea;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField WebsiteInputField;
    private javax.swing.JLabel WebsiteLabel;
    // End of variables declaration//GEN-END:variables
}
